apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
    type: front-end
spec:
  replicas: 5
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
      - name: my-container
        image: python
        command:
        - sleep
        - "3600"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"


