apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
spec:
  containers:
  - image: kodekloud/webapp-color
    name: webapp-color
    resources:
    limits:
        memory: "256Mi"
        cpu: "500m"
    requests:
        memory: "128Mi"
        cpu: "250m"
  envFrom:
    - configMapRef:
        name: cofigmap.yaml
