apiVersion: v1
kind: Pod
metadata:
  name: yellow
  namespace: default
  labels:
    app: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
  - name: gold
    image: redis 
    resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
    command:
      - sleep
      - "1000"
