apiVersion: v1
kind: Pod
metadata: 
  name: webapp-green
  labels:
    name: webapp-green
spec:
  containers:
  - name: webapp-green-container
    image: kodekloud/webapp-color
    args: ["--color","green"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

