apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  containers:
  - name: ubuntu-sleeper-2
    image: ubuntu
    command:
    - sleep
    - "5000" 

    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

