apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name:  developer 
rules: 
  - apiGroups: [""]
    resources: ["Pod"]
    verbs: ["list" , "get" , "create", " update", "delete"]
    namespace: ["blue"]
  
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]