apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    name: bee
spec:
  containers:
  - name: bee-container
    image: nginx
    resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"

